### ISSUE TITLE
Boxee Box restarting as trying to open the apps

### ISSUE THREAD

**Issue by indigenius** [boxeehacks/boxeehack#525]
Boxee box rebooting itself after clicking on the apps menu.
Throwing error boxeehack_server.py failed.

**Comment by kreso13** [comment]
When I have removed USB stick with plus installation, this problem was resolved. Hope it will help you too.

**Comment by indigenius** [comment]
I tried...with USB stick removed...but doesnt seem to solve the problem.

**Comment by Gems** [comment]
I've plugged USB stick, ran uninstall.sh through telnet/busybox, reinstalled boxeehacks and then apps starts work normal.
